# -*- coding: utf-8 -*-
"""Tsne.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11iqaTgnE4Hcxo0BYwALq2io9TFaSTxfO
"""

import os
import pdb
import numpy as np
from scipy import io
# !pip install MulticoreTSNE
from MulticoreTSNE import MulticoreTSNE as TSNE
from matplotlib import pyplot as plt
import matplotlib
import seaborn as sns
import time



t_mask_blur_feat = "/home/dipesh/Desktop/age-gender/npy_feats/t_mask_blur_feat.npy"
t_mask_noblur_feat = "/home/dipesh/Desktop/age-gender/npy_feats/t_mask_noblur_feat.npy"
t_nomask_blur_feat = "/home/dipesh/Desktop/age-gender/npy_feats/t_nomask_blur_feat.npy"
t_nomask_noblur_feat = "/home/dipesh/Desktop/age-gender/npy_feats/t_nomask_noblur_feat.npy"

mask_blur_feat = np.load(t_mask_blur_feat)
mask_noblur_feat = np.load(t_mask_noblur_feat)
nomask_blur_feat = np.load(t_nomask_blur_feat)
nomask_noblur_feat = np.load(t_nomask_noblur_feat)

print("mask_blur_feat shape {}".format(mask_blur_feat.shape))
print("mask_noblur_feat shape {}".format(mask_noblur_feat.shape))
print("nomask_blur_feat shape {}".format(nomask_blur_feat.shape))
print("nomask_noblur_feat shape {}".format(nomask_noblur_feat.shape))


all_features = np.concatenate((mask_blur_feat, mask_noblur_feat, nomask_blur_feat, nomask_noblur_feat), axis = 0)

dataset_label = np.zeros((all_features.shape[0],1))
dataset_label[mask_blur_feat.shape[0]:mask_blur_feat.shape[0]+ mask_noblur_feat.shape[0]] = 1
dataset_label[mask_blur_feat.shape[0]+ mask_noblur_feat.shape[0]:mask_blur_feat.shape[0]+ mask_noblur_feat.shape[0]+nomask_blur_feat.shape[0]] = 2
dataset_label[mask_blur_feat.shape[0]+ mask_noblur_feat.shape[0]+nomask_blur_feat.shape[0]:] = 3

start_time = time.time()

tsne = TSNE(n_jobs=16)

embeddings = tsne.fit_transform(all_features)
vis_x = embeddings[:, 0]
vis_y = embeddings[:, 1]
sns.set(rc={'figure.figsize':(11.7,8.27)})
NUM_CLASSES = 4
palette = sns.color_palette("bright", NUM_CLASSES)

plot = sns.scatterplot(vis_x, vis_y, hue=dataset_label[:,0], legend='full', palette=palette)
pdb.set_trace()
plt.legend(["mask_blur_feat", "mask_noblur_feat", "nomask_blur_feat", "nomask_noblur_feat"], loc='lower right')

plt.savefig("mask_no-mask_blur_no-blur_tsne.png")
print("--- {} mins {} secs---".format((time.time() - start_time)//60,(time.time() - start_time)%60))